spring:
  application:
    name: imageAnalysis-AI-service

  docker:
    compose:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      max-lifetime: 300000
      idle-timeout: 300000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090
  address: 0.0.0.0

clients:
  organization-service:
    base-url: ${ORGANIZATION_SERVICE_BASE_URL:http://railsafe-organization-service:8083}

  risk-service:
    base-url: ${RISK_SERVICE_BASE_URL:http://railsafe-risk-service:8082}

  task-service:
    base-url: ${TASK_SERVICE_BASE_URL:http://railsafe-task-service:8084}

  base44-bridge:
    base-url: ${BASE44_BRIDGE_BASE_URL:http://railsafe-base44-bridge:3001}

logging:
  level:
    root: info
    org.hibernate.SQL: debug